{% set name = "anastruct" %}
{% set version = "1.0b1" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source: 
  git_rev: https://github.com/ritchie46/anaStruct/releases
  git_url: https://github.com/ritchie46/anaStruct.git
 
build:
  number: 0

requirements:
  build:
    - cython
    - python
    - setuptools
    - matplotlib
    - numpy
    - plotly
  run:
    - python
    - matplotlib
    - numpy
    - plotly

test:
  imports:
    - anastruct
    - anastruct.cython
    - anastruct.fem
    - anastruct.fem.cython
    - anastruct.fem.examples
    - anastruct.material

about:
  home: https://ritchievink.com
  license: GPL-3.0
  license_family: GPL3
  license_file: ''
  summary: structural engineering package
  description: ''
  doc_url: ''
  dev_url: ''


